class CreateProductLiving < ActiveRecord::Migration
  def change
    create_table :product_living do |t|
      t.integer :ProductNo
      t.string :Product
      t.string :SKU
      t.string :Oem
      t.string :Supplier
      t.string :ProductType
      t.float :Price
      t.float :PriceRetail
      t.float :PriceWithoutShipping
      t.float :Cost
      t.string :Map
      t.string :Taxable
      t.string :Surcharge
      t.string :SurchargeTitle
      t.string :Shipping
      t.float :Shipping2
      t.string :ShippingExemptInd
      t.string :SaleExclude
      t.float :Quantity
      t.integer :Unit
      t.string :ItemPerPackage
      t.string :Threshold
      t.string :Weight
      t.string :Length
      t.string :Height
      t.string :Width
      t.string :ItemLength
      t.string :ItemHeight
      t.string :ItemWidth
      t.string :ItemWeight
      t.string :ContainerCode
      t.text :Brief
      t.text :Description
      t.string :Subscription
      t.string :Template
      t.string :ListingTemplate
      t.text :HighLight1
      t.text :HighLight2
      t.text :HighLight3
      t.text :HighLight4
      t.text :HighLight5
      t.text :HighLight6
      t.text :HighLight7
      t.text :HighLight8
      t.string :Active
      t.string :AuthReq
      t.string :Isbn
      t.string :Brand
      t.string :Mpn
      t.string :Upc
      t.string :Ean
      t.string :eBayProductId
      t.string :ProductReferenceId
      t.string :Condition
      t.string :Media
      t.string :NaturalSearchKeywords
      t.string :NaturalSearchDescription
      t.string :Category
      t.integer :Category2
      t.integer :Category3
      t.string :Keywords
      t.string :GoogleCategory
      t.string :GoogleAgeGroup
      t.string :GoogleGender
      t.string :Attribute1SharedName
      t.string :Attribute1Label
      t.text :Attribute1Values
      t.string :Attribute1DisplayType
      t.string :Attribute2SharedName
      t.string :Attribute2Label
      t.text :Attribute2Values
      t.string :Attribute2DisplayType
      t.string :Attribute3SharedName
      t.string :Attribute3Label
      t.text :Attribute3Values
      t.string :Attribute3DisplayType
      t.string :Attribute4SharedName
      t.string :Attribute4Label
      t.text :Attribute4Values
      t.string :Attribute4DisplayType
      t.string :Attribute5SharedName
      t.string :Attribute5Label
      t.text :Attribute5Values
      t.string :Attribute5DisplayType
      t.string :Attribute6SharedName
      t.string :Attribute6Label
      t.text :Attribute6Values
      t.string :Attribute6DisplayType
      t.string :Attribute7SharedName
      t.string :Attribute7Label
      t.text :Attribute7Values
      t.string :Attribute7DisplayType
      t.string :Attribute8SharedName
      t.string :Attribute8Label
      t.text :Attribute8Values
      t.string :Attribute8DisplayType
      t.string :Attribute9SharedName
      t.string :Attribute9Label
      t.string :Attribute9Values
      t.stringAttribute10SharedName :Attribute9DisplayType
      t.string :Attribute10Label
      t.string :Attribute10Values
      t.string :Attribute10DisplayType
      t.string :MediaItem1
      t.string :MediaItem2
      t.string :MediaItem3
      t.string :MediaItem4
      t.string :MediaItem5
      t.string :MediaItem6
      t.string :MediaItem7
      t.string :MediaItem8
      t.string :MediaItem9
      t.string :MediaItem10
      t.string :MediaItem11
      t.string :MediaItem12
      t.string :MediaItem13
      t.string :MediaItem14
      t.string :MediaItem15
      t.string :MediaItem16
      t.integer :thumb_number
      t.integer :post_status
      t.datetime :createdtime
      t.timestamp :updatedtime
      t.timestamp :puplictime
      t.integer :drafts
      t.datetime :starttime
      t.datetime :endtime
      t.float :ContainerLoad
      t.string :EstimatedArrival
      t.text :DaysReturnPolicy
      t.string :CompareSite1
      t.float :CompareValue1
      t.string :CompareLink1
      t.string :CompareSite2
      t.float :CompareValue2
      t.string :CompareLink2
      t.string :CompareSite3
      t.float :CompareValue3
      t.string :CompareLink3
      t.string :ShipFrom
      t.string :ShipWithin
      t.string :OptionName1
      t.text :OptionValues1
      t.string :OptionName2
      t.text :OptionValues2
      t.string :OptionName3
      t.text :OptionValues3
      t.integer :ViewCatalog
      t.integer :InSaleEvent
      t.string :Note
      t.integer :Customsize
      t.text :OptionImages
      t.integer :flashsale
      t.boolean :is_iphone5_case
      t.string :MetaDescription
      t.string :SeoUrl
      t.string :TitleSeo
      t.float :shipexpress
      t.integer :isDeal
      t.string :state
      t.string :EstimatedArrival2
      t.string :SpecificationsTitle
      t.string :ShippingTitle
      t.integer :IsFreight
      t.float :Lenght1
      t.float :Lenght2
      t.float :Lenght3
      t.float :Lenght4
      t.float :Lenght5
      t.float :Height1
      t.float :Height2
      t.float :Height3
      t.float :Height4
      t.float :Height5
      t.float :Width1
      t.float :Width2
      t.float :Width3
      t.float :Width4
      t.float :Width5
      t.float :Weight1
      t.float :Weight2
      t.float :Weight3
      t.float :Weight4
      t.float :Weight5
      t.integer :sort
      t.integer :visible
      t.string :Hightline
      t.string :warranty
      t.string :tag_color
      t.float :ShipingFedex
      t.string :OptionCost
      t.float :DropShip
      t.integer :export_dropship
      t.string :InternetDistribution
      t.float :DropShipFree
      t.string :FileUpload
      t.integer :submitted_product
      t.integer :export_beba
      t.integer :export_banbeba
      t.string :CategorySears
      t.integer :request_user

      t.timestamps
    end
  end
end
