class ProductLiving < ActiveRecord::Base
  self.pluralize_table_names = false
  attr_accessible :Active, :Attribute10DisplayType, :Attribute10Label, :Attribute10Values, :Attribute1DisplayType, :Attribute1Label, :Attribute1SharedName, :Attribute1Values, :Attribute2DisplayType, :Attribute2Label, :Attribute2SharedName, :Attribute2Values, :Attribute3DisplayType, :Attribute3Label, :Attribute3SharedName, :Attribute3Values, :Attribute4DisplayType, :Attribute4Label, :Attribute4SharedName, :Attribute4Values, :Attribute5DisplayType, :Attribute5Label, :Attribute5SharedName, :Attribute5Values, :Attribute6DisplayType, :Attribute6Label, :Attribute6SharedName, :Attribute6Values, :Attribute7DisplayType, :Attribute7Label, :Attribute7SharedName, :Attribute7Values, :Attribute8DisplayType, :Attribute8Label, :Attribute8SharedName, :Attribute8Values, :Attribute9DisplayType, :Attribute9Label, :Attribute9SharedName, :Attribute9Values, :AuthReq, :Brand, :Brief, :Category, :Category2, :Category3, :CategorySears, :CompareLink1, :CompareLink2, :CompareLink3, :CompareSite1, :CompareSite2, :CompareSite3, :CompareValue1, :CompareValue2, :CompareValue3, :Condition, :ContainerCode, :ContainerLoad, :Cost, :Customsize, :DaysReturnPolicy, :Description, :DropShip, :DropShipFree, :Ean, :EstimatedArrival, :EstimatedArrival2, :FileUpload, :GoogleAgeGroup, :GoogleCategory, :GoogleGender, :Height, :Height1, :Height2, :Height3, :Height4, :Height5, :HighLight1, :HighLight2, :HighLight3, :HighLight4, :HighLight5, :HighLight6, :HighLight7, :HighLight8, :Hightline, :InSaleEvent, :InternetDistribution, :IsFreight, :Isbn, :ItemHeight, :ItemLength, :ItemPerPackage, :ItemWeight, :ItemWidth, :Keywords, :Lenght1, :Lenght2, :Lenght3, :Lenght4, :Lenght5, :Length, :ListingTemplate, :Map, :Media, :MediaItem1, :MediaItem10, :MediaItem11, :MediaItem12, :MediaItem13, :MediaItem14, :MediaItem15, :MediaItem16, :MediaItem2, :MediaItem3, :MediaItem4, :MediaItem5, :MediaItem6, :MediaItem7, :MediaItem8, :MediaItem9, :MetaDescription, :Mpn, :NaturalSearchDescription, :NaturalSearchKeywords, :Note, :Oem, :OptionCost, :OptionImages, :OptionName1, :OptionName2, :OptionName3, :OptionValues1, :OptionValues2, :OptionValues3, :Price, :PriceRetail, :PriceWithoutShipping, :Product, :ProductNo, :ProductReferenceId, :ProductType, :Quantity, :SKU, :SaleExclude, :SeoUrl, :ShipFrom, :ShipWithin, :ShipingFedex, :Shipping, :Shipping2, :ShippingExemptInd, :ShippingTitle, :SpecificationsTitle, :Subscription, :Supplier, :Surcharge, :SurchargeTitle, :Taxable, :Template, :Threshold, :TitleSeo, :Unit, :Upc, :ViewCatalog, :Weight, :Weight1, :Weight2, :Weight3, :Weight4, :Weight5, :Width, :Width1, :Width2, :Width3, :Width4, :Width5, :createdtime, :drafts, :eBayProductId, :endtime, :export_banbeba, :export_beba, :export_dropship, :flashsale, :isDeal, :is_iphone5_case, :post_status, :puplictime, :request_user, :shipexpress, :sort, :starttime, :state, :submitted_product, :tag_color, :thumb_number, :updatedtime, :visible, :warranty
  
  def self.search(user_id, keyword, category, start, limit)         
      ProductLiving.find(:all, :order => "updatedtime DESC", :offset => start, :limit => limit, :conditions => ['Category like ? or Category2 like ? or Category3 like ? and post_status = 4 and visible = 1 and drafts = 1', "%#{category}%", "%#{category}%", "%#{category}%"])          
  end
  
end
